<h1>Réservation Massage</h1>
<div class="main-reservation">
    <div class="auth">
        <p>Veuillez vous authentifier pour réserver un massage</p>
        <?php include_once 'Views/auth/login.phtml'; ?>
    </div>
    <div class="auth">
        <p>Pas encore de compte? Inscrivez-vous</p>
        <?php include_once 'Views/auth/register.phtml'; ?>
    </div>
</div>

<script type="module" src="public/js/auth.js"></script> 
