<h3>Inscription</h3>
<form action="index.php?route=register" id="register_form" method="POST" class="register-form">

    <input 
        type="hidden" 
        name="csrf_token_register" 
        value="<?= htmlspecialchars($_SESSION['csrf_token_register'],ENT_QUOTES) ?>"
    />  
<fieldset>
    <label for="register_lastname">Nom </label>
    <input 
        type="text" 
        name="user_lastname" 
        minlength="2" 
        id="register_lastname" 
        title="Entrez votre Nom (2 caractères minimum)"
        required 
    />


    <label for="register_firstname">Prenom </label>
    <input 
        type="text" 
        name="user_firstname" 
        minlength="2" 
        id="register_firstname" 
        title="Entrez votre Prénom (2 caractères minimum)"
        required
    />
</fieldset>
<fieldset>

    <label for="register_number">Numéro de telephone</label>
    <input 
        type="tel" 
        name="user_number" 
        id="register_number" 
        title = "Entrez votre numéro de téléphone. 10 à 12 chiffres."
        required
    />


    <label for="register_mail">Email</label>
    <input 
        type="email" 
        name="user_mail" 
        id="register_mail" 
        title="Entrez votre email"
        placeholder="   @   .com"
        required
    />
</fieldset>
<fieldset>
    <label for="register_password">Mot de passe</label>
    <div class="password-verif">
        <input 
            type="password" 
            name="user_password" 
            id="register_password" 
            minlength = "8"
            title="Doit contenir au moins un chiffre, un caractère spécial (&@!?;()), et au moins 8 caractères ou plus"
            placeholder=" 8 caractères minimum "
            required
            <?php if(!empty($_SESSION['formErrors']['user_password'])): ?>class="error"<?php endif; ?>
        /> 
        <button 
            type="button" 
            id="btnShowPasswordRegister"
            title="Afficher le mot de passe"
            class="btnShowPassword">
            <svg id="eye" xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye-off"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path><line x1="1" y1="1" x2="23" y2="23"></line>
            </svg> 
        </button>
    </div>
</fieldset>
    <div id="errorsRegister"></div>
    <button 
        type="submit" 
        id="btnRegister"
        class="btnSubmitAuth"
        title="Bouton pour valider l'incription">S'inscrire
    </button>
</form>

<?php 
if (!empty($_SESSION['formErrors'])): ?>
    <?php foreach ($_SESSION['formErrors'] as $error): ?>
        <div class='error'>
            <?= htmlspecialchars($error); ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

