<?php if (!empty($_SESSION['connectedUser'])): ?>
    <div class="welcome">
        <p>Bienvenue <?= htmlspecialchars($_SESSION['connectedUser']['firstname'], ENT_QUOTES)?> sur votre espace personnel </p>
        <button type="button" id="btnLogout" class="btn-logout">Déconnexion</button>
    </div>
<?php endif; ?>

<?php include_once('Views/admin/nav.phtml');?>

<script type="module" src="public/js/logoutConfirmation.js"></script>
