<?php if (!empty($_SESSION['connectedUser'])): ?>
    <div class="welcome">
        <p>Bienvenue <?= htmlspecialchars($_SESSION['connectedUser']['firstname'], ENT_QUOTES)?> sur votre espace personnel </p>
        <button type="button" id="btnLogout" class="btn-logout">
            <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                <polyline points="16 17 21 12 16 7"></polyline>
                <line x1="21" y1="12" x2="9" y2="12"></line>
            </svg>
        </button>
    </div>
<?php endif; ?>

<?php include_once('Views/admin/nav.phtml');?>

<script type="module" src="public/js/logoutConfirmation"></script>
