<nav class=nav-connect>
     <ul>
        <li><a href="index.php?route=admin_massage">Gestion de la Page Massage</a></li>
        <li><a href="index.php?route=admin_tea">Gestion du Salon de thé</a></li>
        <li><a href="index.php?route=admin_reservation">Affichage des reservations de massage</a></li>
        <li><a href="index.php?route=admin_userManagement">Gestion des utilisateurs</a></li>
        <li><a href="index.php?route=admin_message">Gestion des messages</a></li> 
    </ul>
</nav>