<nav class=nav-connect>
     <ul>
        <li><a href="index.php?route=admin_massage">Gestion de la page Massage</a></li>
        <li><a href="index.php?route=admin_tea">Gestion de la page Salon de thé</a></li>
        <li><a href="index.php?route=admin_reservation">Gestion des reservations</a></li>
        <li><a href="index.php?route=admin_userManagement">Gestion des utilisateurs</a></li>
        <li><a href="index.php?route=admin_message">Gestion des messages</a></li> 
    </ul>
</nav>