<?php include_once('Views/admin/index.phtml');?>

<h1>Gestion du Salon de thé</h1>

<button id="showAddProduct" class="btn-green">Ajouter un produit</button>

<form id="productForm" class="form-product" action="index.php?route=submitProduct" method="POST">
    
    <input 
        type="hidden" 
        name="csrf_token_product" 
        value="<?= htmlspecialchars($_SESSION['csrf_token_product'], ENT_QUOTES) ?>"
    />

    <label for="name">Nom du produit</label>
    <input 
        type="text" 
        id="name" 
        name="product_name"
        required
    />

    <label for="product_type"> Catégorie</label>
    <select id="product_type" name="product_type" required>
    <option value="">Sélectionnez une catégorie</option>
        <option value="7">Cafés</option>
        <option value="8">Thés & Infusions</option>
        <option value="9">Chocolats Chauds</option>
        <option value="10">Rafraichissements</option>
        <option value="11">Gourmandises salées</option>
        <option value="12">Délices de Damas</option>
        <option value="13">Douceurs Sucrées</option>
    </select>

    <label for="description">Description</label>
    <textarea 
        id="description" 
        name="product_info" 
        minlength="10"
        required
    >
    </textarea>

    <label for="product_price">Prix</label>
    <input 
        type="number" 
        step="0.1"
        id="product_price" 
        name="product_price" 
        title="Veuillez entrer uniquement des chiffres." 
        placeholder="Prix en euros"
        required
    />

    <input 
        class="btn-green"
        type="submit" 
        title="Validez"
        value="Validez"
    />
</form>

<button id="showAddImg" class="btn">Ajouter une image</button>

<form id="uploadImg" class="form-img" action="index.php?route=submitImage" method="POST" enctype="multipart/form-data" >
    <input 
            type="hidden" 
            name="csrf_token_image" 
            value="<?= htmlspecialchars($_SESSION['csrf_token_image'], ENT_QUOTES) ?>"
        />

    <label for="image">Choisissez une image (format jpg, jpeg, png, gif)</label>
        <input 
            type="file" 
            id="image" 
            name="upload_image" 
            required
        />

    <label for="image_type"> Catégorie</label>
    <select id="image_type" name="image_type" required>
        <option value="">Sélectionnez une catégorie</option>
        <option value="7">Cafés</option>
        <option value="8">Thés & Infusions</option>
        <option value="9">Chocolats Chauds</option>
        <option value="10">Rafraichissements</option>
        <option value="11">Gourmandises salées</option>
        <option value="12">Délices de Damas</option>
        <option value="13">Douceurs Sucrées</option>
    </select>

    <input 
        type="submit" 
        name="Ajoutez" 
        value="Ajouter"
        class="btn">
</form>

<?php if (!empty($_SESSION['messageSent'])): ?>
    <div class='message'>
        <?= htmlspecialchars($_SESSION['messageSent']); ?>
        <?php unset($_SESSION['messageSent']); ?>
    </div>
<?php endif; ?>

<?php if (!empty($_SESSION['formErrors'])): ?>
    <?php foreach ($_SESSION['formErrors'] as $error): ?>
        <div class='error'>
            <?= htmlspecialchars($error); ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="card-img">
    <?php foreach ($images as $img): ?>
        <p><img class="product-image" src="public/upload/<?= htmlspecialchars($img['file_name']) ?>" alt="Image du produit">
    <?php endforeach; ?>
</div>
<section class="flexTea">
    <h2>Cafés</h2>
    <div class="card">
        <?php foreach ($productsByType[7] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Thés & Infusions</h2>
    <div class="card">
        <?php foreach ($productsByType[8] as $product): ?> 
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Chaucolats Chauds</h2>
    <div class="card">
        <?php foreach ($productsByType[9] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Rafraichissements</h2>
    <div class="card">
        <?php foreach ($productsByType[10] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Gourmandises salées</h2>
    <div class="card">
        <?php foreach ($productsByType[11] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Délices de Damas</h2>
    <div class="card">
        <?php foreach ($productsByType[12] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>

    <h2>Douceurs Sucrées</h2>
    <div class="card">
        <?php foreach ($productsByType[13] as $product): ?>
            <div class="card-product">
                <p>Nom : <?= htmlspecialchars($product['name']) ?></p>
                <p>Description : <?= htmlspecialchars($product['description']) ?></p> 
                <p>Prix : <?= htmlspecialchars($product['price']) ?>€</p>
                <p>Enregristrée le : <?= htmlspecialchars($product['created_at']) ?></p>
                <p>Modifié le : <?= htmlspecialchars($product['updated_at']) ?></p>
            </div> 
    <?php endforeach; ?>
    </div>
</section>
<script type="module" src="public/js/adminProduct.js"></script>