<?php if (!empty($_SESSION['connectedUser'])): ?>
    <div class="welcome">
        <p>Bienvenue <?= htmlspecialchars($_SESSION['connectedUser']['firstname'], ENT_QUOTES)?> sur votre espace personnel </p>
        
        <button type="button" id="btnLogout" class="btn-logout">Déconnexion
        </button>
    </div>
<?php endif; ?>

<?php if (!empty($_SESSION['errorDelete'])): ?>
    <p><?= htmlspecialchars($_SESSION['errorDelete'], ENT_QUOTES) ?></p>
    <?php unset($_SESSION['errorDelete']); ?>
<?php endif; ?>

<?php include_once('Views/user/nav.phtml');?>

<script type="module" src="public/js/logoutConfirmation.js"></script>



