<section>
    <h1> Bienvenue chez Ikigai </h1>
    <div class="home">
        <div class=home-img1>
            <img src="public/images/commerce.png" alt="photo lieu ikigai">
        </div>
        <div class=home-text>
            <p>Bienvenue dans notre salon de thé et spa, un espace dédié à l'harmonie du corps et de l'esprit. Fondé par deux passionnées, une talentueuse barista et une experte masseuse, notre salon se distingue par la fusion unique du plaisir du thé et des bienfaits revitalisants des massages.</p>
            <p>Notre barista, avec une passion débordante pour les arômes et les saveurs, crée une expérience sensorielle exceptionnelle à travers une sélection exquise de thés du monde entier. Chaque tasse est préparée avec soin, offrant une pause délicieusement apaisante à nos visiteurs.</p>
            <p>D'autre part, notre masseuse qualifiée, inspirée par l'ancienne sagesse japonaise, intègre le concept d'ikigai dans chaque séance de massage. L'ikigai, qui signifie "raison d'être" en japonais, guide notre approche holistique pour aider nos clients à trouver l'équilibre parfait entre passion, vocation, profession et mission.</p>
            <p>Que vous veniez chercher une pause sereine pour déguster un thé raffiné ou que vous souhaitiez bénéficier des bienfaits régénérants d'un massage, notre salon est conçu pour vous offrir un havre de paix où votre bien-être est notre priorité.</p>
            <p>Rejoignez-nous dans cette aventure où la délicatesse du thé se marie harmonieusement avec les bienfaits thérapeutiques des massages, créant ainsi un espace où vous pouvez cultiver votre propre ikigai, votre source de joie et d'épanouissement </p>
        </div>
    </div>  
    <h2>Présentation de Notre Talentueuse Équipe</h2>

    <div class="home2"> 
        <div class=home-img2>
            <img src="public/images/photo_proprio.jpg" alt="photo de la barista et de la masseuse">
        </div>
        <div class=home-text>
            <p>Rencontrez notre équipe exceptionnelle qui allie l'art du thé, du café et des massages pour offrir une expérience unique. Notre barista, avec huit années de dévouement à l'univers raffiné du thé et du café, incarne l'âme même de notre salon. Son parcours a été marqué par la perfection, avec des mélanges uniques qui captivent les sens. Grâce à une récente formation à l'Alchimiste à Bordeaux, elle a enrichi sa compréhension des arômes et des techniques de préparation, excellant désormais dans la création de boissons d'une qualité exceptionnelle.</p>
            <p>Complétant cette équipe exceptionnelle, notre masseuse, forte d'une expérience diversifiée, a débuté son parcours dans des spas renommés avant de fusionner son amour pour les massages avec l'art délicat du thé. En tant qu'entrepreneure audacieuse, elle a créé une expérience immersive pour nos clients. Son bagage professionnel dans des spas de prestige lui confère une maîtrise des techniques de massage relaxantes et revitalisantes. Son approche personnalisée, inspirée de l'équilibre et de la détente, offre à nos visiteurs une évasion bienvenue du tumulte quotidien.</p>
            <p>Venez découvrir l'harmonie parfaite entre l'art authentique du thé et du café, orchestré par notre barista passionnée, et l'expérience relaxante offerte par notre talentueuse masseuse.</p>
        </div>
    </div>
</section>

 