<div class="footer">
    <div class="logoFooter">
        <img src="./public/images/logo.png" alt="logo ikigai" loading="lazy">
    </div>
    <div class="lien">
        <div>
            <p>
                <a title="lien vers formulaire de contact" href="index.php?route=contact" class="element">Une question? N'hesitez pas!</a>
            </p>
        </div>

        <div class="horaire">
            <a title="lien vers Horaires" href="index.php?route=contact#horaire">
                <p class="element">Horaires</p>
            </a>
        </div>

        <div>
            <p>
                <a title="lien vers adresse" href="index.php?route=contact" class="element">Adresse</a>
            </p>
        </div>
    </div>
    <div class="resauxSociaux">
        <a href="https://fr-fr.facebook.com" title="lien vers facebook">
            <img src="public/images/facebook.png" alt="Facebook">
        </a>
        <a href="https://www.instagram.com" title="lien vers instagram">
            <img src="public/images/instagram.png" alt="Instagram">
        </a>
    </div>
</div>