<div>
    <h3>Horaires</h3>
    <p>Lundi-Mardi : Fermée</p>
    <div class="sub-info">
        <div>
            <h4>Massage</h4>
            <p>Mercredi-Dimanche : 11h-21h</p> 
        </div>
        <div>
            <h4>Salon de thé</h4>
            <p>Mercredi-Dimanche : 9h-19h</p>   
        </div>
    </div>
</div>
<div>
    <h3>Contact</h3>
    <p>Rue des Ayres <br> 33000 Bordeaux</p>
</div>
<div>
    <h3>Social networks</h3>
    <a href="https://fr-fr.facebook.com" title="lien vers facebook">
        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="blue" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>
    </a>
    <a href="https://www.instagram.com" title="lien vers instagram">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="pink" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>
    </a>
</div>