<div class="nav-container ">
  <nav class="hamburger-menu">
    <div class="fixed-nav ">

      <div class="logo-display">
        <img src="./public/images/logo1.png" alt="logo ikigai" loading="lazy">
        <img src="./public/images/logo2.png" alt="logo ikigai ligne" loading="lazy" class="logo2">
      </div>

      <input id="menu__toggle" type="checkbox" />
      <label class="menu__btn" for="menu__toggle">
        <span></span>
      </label>

        <ul class="menu__box">
          <li><a title="lien vers Accueil" class="menu__item" href="index.php?route=home">Accueil</a></li>
          <li><a title="lien vers Salon de thé" class="menu__item" href="index.php?route=teahouse">Salon de Thé</a></li>
          <li><a title="lien vers Massage" class="menu__item" href="index.php?route=massage">Massage</a></li>

          <?php if (empty($_SESSION['connectedUser'])): ?>
            <li><a class="menu__item" href="index.php?route=reservation">Reservation</a></li>

          <?php elseif ($_SESSION['connectedUser']['role_id'] === 2): ?>
            <li><a title="lien vers espace user" class="menu__item" href="index.php?route=user_homepage">Espace Utilisateur</a></li>
            
          <?php elseif ($_SESSION['connectedUser']['role_id'] === 1): ?>
            <li><a title="lien vers espace admin" class="menu__item" href="index.php?route=admin_homepage">Espace Administrateur</a></li>
          <?php endif; ?>

          <li><a title="lien vers page de contact" class="menu__item" href="index.php?route=contact">Contact</a></li>
        </ul>
    </div>
  </nav>
</div>
  





  






