<section class="home-page">    
    <div class="background-img"></div>    
    <h1> I K I G A I </h1>
    <div class=home-text>    
        <p>Bienvenue dans notre salon de thé et spa, un espace dédié à l'harmonie du corps et de l'esprit. Fondé par deux passionnées, une talentueuse barista et une experte masseuse, notre salon se distingue par la fusion unique du plaisir du thé et des bienfaits revitalisants des massages.</p>
        <p>L'ikigai, qui signifie "raison d'être" en japonais, guide notre approche holistique pour aider nos clients à trouver l'équilibre parfait entre passion, vocation, profession et mission.</p>
        <p>Que vous veniez chercher une pause sereine pour déguster un thé raffiné ou que vous souhaitiez bénéficier des bienfaits régénérants d'un massage, notre salon est conçu pour vous offrir un havre de paix où votre bien-être est notre priorité.</p>
        <p>Rejoignez-nous dans cette aventure où la délicatesse du thé se marie harmonieusement avec les bienfaits thérapeutiques des massages, créant ainsi un espace où vous pouvez cultiver votre propre ikigai, votre source de joie et d'épanouissement </p>
    </div>

    <div class="home"> 
        <div class="home-img">
            <img src="public/images/photo_proprio.jpg" alt="photo de la barista et de la masseuse">
        </div>
        <div class="home-equipe">    
            <h2>Notre Équipe</h2>
            <p>Notre barista, avec huit années de dévouement à l'univers raffiné du thé et du café, incarne l'âme même de notre salon.
            <br>Grâce à une récente formation à l'Alchimiste à Bordeaux, elle a enrichi sa compréhension des arômes et des techniques de préparation, excellant désormais dans la création de boissons d'une qualité exceptionnelle.
            <br>Elle créait une expérience sensorielle exceptionnelle à travers une sélection exquise de thés du monde entier. 
            <br>Chaque tasse est préparée avec soin, offrant une pause délicieusement apaisante à nos visiteurs.</p>
            
            <p>Notre masseuse, forte d'une expérience diversifiée, a débuté son parcours dans des spas renommés qui lui ont permis de maîtriser des techniques de massage relaxantes et revitalisantes. 
            <br>Son approche personnalisée, inspirée de l'équilibre et de la détente, offre à nos visiteurs une évasion bienvenue. 
            <br>Inspirée par l'ancienne sagesse japonaise, elle intègre le concept d'ikigai dans chaque séance de massage. </p>
        </div>
    </div>
</section>

 <script src="public/js/modules/animation.js"></script>